import React from 'react';
import { ShieldCheck, Globe, Target, Award, Sparkles, Heart } from 'lucide-react';
import { AnimatedLogo } from '../components/common/AnimatedLogo';

interface AboutPageProps {
  onNavigate: (route: string) => void;
}

export const AboutPage: React.FC<AboutPageProps> = ({ onNavigate }) => {
  return (
    <div className="container" style={{ paddingTop: '3rem', paddingBottom: '5rem', maxWidth: '880px' }}>
      <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
        <div style={{ display: 'inline-block', marginBottom: '1.25rem' }}>
          <AnimatedLogo size="lg" showTagline />
        </div>
        <h1 style={{ fontSize: '2.5rem', fontWeight: 800, marginBottom: '0.75rem' }}>
          Empowering International IELTS Candidates
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1.15rem', lineHeight: 1.6 }}>
          IELTS NovaPrep is an independent, production-ready international preparation and self-improvement platform designed to make realistic, high-quality test preparation accessible to learners worldwide.
        </p>
      </div>

      {/* Core Mission Cards */}
      <div className="grid-2" style={{ marginBottom: '3rem' }}>
        <div className="card" style={{ padding: '2rem' }}>
          <div style={{ width: '44px', height: '44px', borderRadius: 'var(--radius-sm)', backgroundColor: 'var(--brand-primary-light)', color: 'var(--brand-primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1rem' }}>
            <Globe size={22} />
          </div>
          <h3 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.5rem' }}>
            Global Accessibility & Neutrality
          </h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
            Our platform uses internationally understandable English, standard time/date conventions, and diverse accent models (British, American, Australian, Canadian). Whether preparing from Pakistan, Nigeria, Vietnam, Brazil, or the United Kingdom, candidates receive an authentic preparation experience.
          </p>
        </div>

        <div className="card" style={{ padding: '2rem' }}>
          <div style={{ width: '44px', height: '44px', borderRadius: 'var(--radius-sm)', backgroundColor: 'var(--brand-accent-light)', color: 'var(--brand-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1rem' }}>
            <Sparkles size={22} />
          </div>
          <h3 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.5rem' }}>
            Active Feedback Learning Loop
          </h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
            We reject passive rote-learning and hollow memorized templates. Our curriculum teaches genuine communicative competence through live acoustic recording, heuristic writing feedback, and an automated Mistake Book.
          </p>
        </div>
      </div>

      {/* Independent IELTS Disclaimer Box */}
      <div
        id="disclaimer"
        className="card"
        style={{
          padding: '2rem',
          backgroundColor: 'var(--bg-subtle)',
          border: '1.5px solid var(--border-strong)',
          marginBottom: '3rem',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
          <ShieldCheck size={28} style={{ color: 'var(--brand-primary)' }} />
          <h3 style={{ fontSize: '1.3rem', fontWeight: 800, margin: 0 }}>
            Official Independent Platform Disclaimer
          </h3>
        </div>

        <div style={{ fontSize: '0.92rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
          <p style={{ marginBottom: '0.75rem' }}>
            <strong>"IELTS NovaPrep is an independent IELTS preparation and practice platform. It is not affiliated with or endorsed by IELTS, British Council, IDP Education or Cambridge."</strong>
          </p>
          <p style={{ marginBottom: '0.75rem' }}>
            All practice questions, diagnostic tests, listening tracks, reading passages, and study guides published on IELTS NovaPrep are 100% original educational works created independently. We do not use copyrighted official IELTS materials or proprietary exam papers.
          </p>
          <p>
            Any scores, band ratings, or assessments generated by our automated analyzers are estimated practice indicators intended solely for self-guided improvement and must never be represented as official IELTS band certifications.
          </p>
        </div>
      </div>

      <div style={{ textAlign: 'center' }}>
        <button onClick={() => onNavigate('/practice')} className="btn btn-primary btn-lg">
          Start Practicing Now
        </button>
      </div>
    </div>
  );
};
